project:
  type: book

book:
  title: "Introduction to Statistics"
  author: "Fred Ho"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - chapters/04-prep1.qmd
    - chapters/05-prep2.qmd
    - chapters/07-descriptive.qmd
    - chapters/08-estimation.qmd
    - chapters/09-comparison.qmd
    - chapters/10-regression.qmd
    - chapters/11-adjustment.qmd
    - chapters/12-summary.qmd
  appendices:
    - chapters/99-glossary.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-before-body:
      - images/cover-titlepage.tex
    header-includes:
      - \renewcommand{\maketitle}{}

